guage: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"

addons:
  apt:
    update: true
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - sudo chown -R $USER /usr/local/lib/python3.4
  - sudo apt-get install python3-pip

# command to install dependencies
install:
  - sudo pip install pymongo spacy numpy pytest

# command to run tests
script:
  - pytest src/tests.py
